[package]
name = "rgb"
edition = "2024.beta"
authors = ["Studio Mirai, Inc. (contact@sm.xyz)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
Codec = { git = "https://github.com/sui-potatoes/app.git", subdir = "packages/codec", rev = "main" }

[addresses]
rgb = "0x0"
